services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - ./backend:/app
  frontend:
      build: ./frontend
      ports:
      - "5173:80"
      volumes:
      - ./frontend:/app

# docker pull anjali286/ecoswap:latest  -->>anyone can run this project using this command